name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: "scripts/*.sh"  

      - name: Execute Tests
        run: |
          chmod +x ./test_host-master.sh
          chmod +x ./test_cluster-master.sh
          ./test_host-master.sh
          ./test_cluster-master.sh          
