name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: azohra/shell-check@master
        with:
          path: "scripts/*.sh"  

      - name: Install CentOS-compatible Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yum-utils

      - name: Execute Tests
        run: |
          chmod +x ./test_host-master.sh   
          chmod +x ./test_cluster-master.sh   
          ./test_host-master.sh            
          ./test_cluster-master.sh            
