name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: rocky linux-v9.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: azohra/shellcheck@master
        with:
          path: "/root/kubernetes-binary-install/scripts/*.sh"  

      - name: Execute Tests
        run: |
          chmod +x ./test_host-master.sh   
          chmod +x ./test_cluster-master.sh   
          ./test_host-master.sh            
          ./test_cluster-master.sh            
