name: Shell Script CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "main"

jobs:
  test-shell-scripts:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
      options: --security-opt seccomp=unconfined --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Rocky Linux Environment
        run: |
          set -euxo pipefail

          # 替换镜像源
          for repo in /etc/yum.repos.d/rocky*.repo; do
            sed -i 's/mirrorlist/#mirrorlist/g' $repo
            sed -i 's|#baseurl=http://dl.rockylinux.org|baseurl=https://mirrors.aliyun.com/rockylinux|g' $repo
          done

          # 安装依赖
          dnf update -y
          dnf install -y epel-release
          dnf install -y git curl tar gzip ansible which \
            bash-completion openssh-clients sudo

          # 统一授权脚本
          find ./scripts -name "*.sh" -exec chmod +x {} \;

      - name: Run Host Tests
        run: ./scripts/test_host-master.sh

      - name: Run Cluster Tests
        run: ./scripts/test_cluster-master.sh

      - name: Security Scan (Trivy)
        run: |
          # 安装指定版本 Trivy
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin v0.50.1
          
          # 仅扫描项目目录
          trivy filesystem --exit-code 1 \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            $GITHUB_WORKSPACE
